[runtime]
log_level="WARNING"
dlthub_telemetry = true
api_base_url = "https://dlthub.dev/api/api"
auth_base_url = "https://dlthub.dev/api/auth"
workspace_id = "3936e510-59c6-46ba-ad15-de7e91f93e39"

[destination.jaffleshop_transformation_destination]
destination_type="duckdb"

[jobs.jaffle_mcp.mcp]
transport = "http"
