[runtime]
log_level="WARNING"
dlthub_telemetry = true
api_base_url = "https://dlthub.test/api/api"
auth_base_url = "https://dlthub.test/api/auth"
workspace_id = "cd1f1ccf-9dd0-41d8-8e62-919b8a5a9984"

[destination.pokeland]
destination_type="duckdb"
