[runtime]
log_level="WARNING"
dlthub_telemetry = true
api_base_url = "https://dlthub.dev/api/api"
auth_base_url = "https://dlthub.dev/api/auth"
workspace_id = "d1bfae42-2d29-4483-a1f8-1219f74bb13b"

[destination.pokeland]
destination_type="duckdb"
