[runtime]
log_level="WARNING"
dlthub_telemetry = true
api_base_url = "https://dlthub.test/api/api"
auth_base_url = "https://dlthub.test/api/auth"
workspace_id = "c83b9697-029f-4715-b394-cbaf9c2e35ac"

[destination.warehouse]
destination_type="duckdb"
